[platformio]
default_envs = disco_f407vg

; Base configuration shared across all environments
[env]
platform = ststm32
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
board_build.f_cpu = 168000000L
build_flags = 
    -DHSE_VALUE=8000000L

; Environment 1: STM32F407VG (Discovery Board / 1MB Flash)
[env:disco_f407vg]
board = disco_f407vg

; Environment 2: STM32F407VE (Black/Blue Pill or custom board / 512KB Flash)
[env:genericSTM32F407VET6]
board = genericSTM32F407VET6
